[package]
name = "content-id"
version = "0.1.0"
authors = ["Jeff R <ruhlio@users.noreply.github.com>"]

[dependencies]
multibase = { path = "../multibase" }
multihash = { path = "../multihash" }
protobuf = "*"
